// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PSI.Core.Infrastructure.DBContext;

namespace PSI.Core.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220427020036_adjust about contract table")]
    partial class adjustaboutcontracttable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PSI.Core.Entities.CodeTable", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CodeGroup")
                        .HasColumnType("text");

                    b.Property<string>("CodeText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsEffective")
                        .HasColumnType("text");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("CodeTables");
                });

            modelBuilder.Entity("PSI.Core.Entities.CustomerCar", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<Guid>("CAR_GUID")
                        .HasColumnType("uuid");

                    b.Property<string>("CAR_NAME")
                        .HasColumnType("text");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CUSTOMER_GUID")
                        .HasColumnType("uuid");

                    b.Property<long>("CUSTOMER_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("IS_EFFECTIVE")
                        .HasColumnType("text");

                    b.Property<string>("REMARK")
                        .HasColumnType("text");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("CustomerCars");
                });

            modelBuilder.Entity("PSI.Core.Entities.CustomerContract", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<Guid>("CONTRACT_GUID")
                        .HasColumnType("uuid");

                    b.Property<string>("CONTRACT_NAME")
                        .HasColumnType("text");

                    b.Property<int>("CONTRACT_STATUS")
                        .HasColumnType("integer");

                    b.Property<string>("CONTRACT_TYPE")
                        .HasColumnType("text");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CUSTOMER_GUID")
                        .HasColumnType("uuid");

                    b.Property<double>("DEAL_UNIT_PRICE")
                        .HasColumnType("double precision");

                    b.Property<double>("DEAL_WEIGHT")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("END_DATETIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EXPIRE_REASON")
                        .HasColumnType("text");

                    b.Property<Guid>("PRODUCT_GUID")
                        .HasColumnType("uuid");

                    b.Property<string>("REMARK")
                        .HasColumnType("text");

                    b.Property<DateTime>("START_DATETIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("CustomerContracts");
                });

            modelBuilder.Entity("PSI.Core.Entities.CustomerContractLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<Guid>("CONTRACT_GUID")
                        .HasColumnType("uuid");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IS_EFFECTIVE")
                        .HasColumnType("text");

                    b.Property<Guid>("PSI_DOC_GUID")
                        .HasColumnType("uuid");

                    b.Property<string>("REMARK")
                        .HasColumnType("text");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("CustomerContractLogs");
                });

            modelBuilder.Entity("PSI.Core.Entities.CustomerInfo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ADDRESS")
                        .HasColumnType("text");

                    b.Property<string>("COMPANY_NAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CONTENT_INFO")
                        .HasColumnType("text");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CUSTOMER_GUID")
                        .HasColumnType("uuid");

                    b.Property<string>("CUSTOMER_NAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IS_CONTRACT")
                        .HasColumnType("boolean");

                    b.Property<string>("IS_EFECTIVE")
                        .HasColumnType("text");

                    b.Property<string>("PSI_TYPE")
                        .HasColumnType("text");

                    b.Property<string>("REMARK")
                        .HasColumnType("text");

                    b.Property<string>("TAX_ID")
                        .HasColumnType("text");

                    b.Property<string>("TITLE")
                        .HasColumnType("text");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("CustomerInfos");
                });

            modelBuilder.Entity("PSI.Core.Entities.ProductItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IS_EFFECTIVE")
                        .HasColumnType("text");

                    b.Property<Guid>("PRODUCT_GUID")
                        .HasColumnType("uuid");

                    b.Property<string>("PRODUCT_NAME")
                        .HasColumnType("text");

                    b.Property<string>("PSI_TYPE")
                        .HasColumnType("text");

                    b.Property<string>("REMARK")
                        .HasColumnType("text");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("PSI.Core.Entities.PurchaseIngredient", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.Property<double>("ItemPercent")
                        .HasColumnType("double precision");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("PurchaseWeighNoteId")
                        .HasColumnType("bigint");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("PurchaseIngredients");
                });

            modelBuilder.Entity("PSI.Core.Entities.PurchaseWeightNote", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal?>("ActualPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CarNo")
                        .HasColumnType("text");

                    b.Property<double?>("CarWeight")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CarWeightTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("DefectiveReason")
                        .HasColumnType("text");

                    b.Property<double>("DefectiveWeight")
                        .HasColumnType("double precision");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric");

                    b.Property<string>("DocNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExcavatorOpEmpNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExcavatorOpTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FacNo")
                        .HasColumnType("text");

                    b.Property<double?>("FinalDefectiveWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("FullWeight")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FullWeightTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HasTax")
                        .HasColumnType("boolean");

                    b.Property<string>("InputType")
                        .HasColumnType("text");

                    b.Property<string>("NoteStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PayTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PayType")
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("ScaleNo")
                        .HasColumnType("text");

                    b.Property<decimal>("ThirdWeightFee")
                        .HasColumnType("numeric");

                    b.Property<double?>("TradeWeight")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("TraficUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("text");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WeightPrice")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.ToTable("PurchaseWeightNotes");
                });

            modelBuilder.Entity("PSI.Core.Entities.SeqTypeConfig", b =>
                {
                    b.Property<string>("SeqType")
                        .HasColumnType("text");

                    b.Property<long>("SeqNo")
                        .HasColumnType("bigint");

                    b.HasKey("SeqType");

                    b.ToTable("SeqTypeConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
