// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSI.Core.Infrastructure.DBContext;

namespace PSI.Core.Migrations.Lite
{
    [DbContext(typeof(LiteContext))]
    [Migration("20221129023534_update db")]
    partial class updatedb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15");

            modelBuilder.Entity("PSI.Core.Entities.CodeTable", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CODE_GROUP")
                        .HasColumnType("TEXT");

                    b.Property<string>("CODE_TEXT")
                        .HasColumnType("TEXT");

                    b.Property<string>("CODE_VALUE")
                        .HasColumnType("TEXT");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("IS_EFFECTIVE")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SORT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CodeTables");
                });

            modelBuilder.Entity("PSI.Core.Entities.CustomerCar", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CAR_GUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CAR_NAME")
                        .HasColumnType("TEXT");

                    b.Property<int>("CAR_NO_TYPE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CUSTOMER_GUID")
                        .HasColumnType("TEXT");

                    b.Property<long>("CUSTOMER_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IS_EFFECTIVE")
                        .HasColumnType("TEXT");

                    b.Property<string>("REMARK")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CustomerCars");
                });

            modelBuilder.Entity("PSI.Core.Entities.CustomerContract", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CONTRACT_GUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CONTRACT_NAME")
                        .HasColumnType("TEXT");

                    b.Property<int>("CONTRACT_STATUS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CONTRACT_TYPE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CUSTOMER_GUID")
                        .HasColumnType("TEXT");

                    b.Property<double>("DEAL_UNIT_PRICE")
                        .HasColumnType("REAL");

                    b.Property<double>("DEAL_WEIGHT")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("END_DATETIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("EXPIRE_REASON")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PRODUCT_GUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("REMARK")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("START_DATETIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CustomerContracts");
                });

            modelBuilder.Entity("PSI.Core.Entities.CustomerContractLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CONTRACT_UNID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("IS_EFFECTIVE")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PSI_DOC_UNID")
                        .HasColumnType("TEXT");

                    b.Property<string>("REMARK")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CustomerContractLogs");
                });

            modelBuilder.Entity("PSI.Core.Entities.CustomerInfo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ADDRESS")
                        .HasColumnType("TEXT");

                    b.Property<string>("COMPANY_NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("CONTENT_INFO")
                        .HasColumnType("TEXT");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CUSTOMER_GUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CUSTOMER_NAME")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IS_CONTRACT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IS_EFFECTIVE")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PSI_TYPE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("REMARK")
                        .HasColumnType("TEXT");

                    b.Property<string>("TAX_ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("TITLE")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CustomerInfos");
                });

            modelBuilder.Entity("PSI.Core.Entities.PS_WreteOff_Record", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("PURCHASE_DOC_NO")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PURCHASE_WEIGHTNOTE_UNID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SALES_DOC_NO")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SALES_WEIGHTNOTE_UNID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("WRITEOFF_ITEM_NAME")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WRITEOFF_PRODUCT_UNID")
                        .HasColumnType("TEXT");

                    b.Property<double>("WRITEOFF_WEIGHT")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("PS_WreteOff_Record");
                });

            modelBuilder.Entity("PSI.Core.Entities.P_Inventory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<int>("ITEM_PERCENT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PRODUCT_ITEM_NAME")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PRODUCT_UNID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PURCHASE_WEIGHTNOTE")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PURCHASE_WEIGHTNOTE_UNID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("REMAINING_WEIGHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("STATUS")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UNIT_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("P_Inventory");
                });

            modelBuilder.Entity("PSI.Core.Entities.ProductItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("IS_EFFECTIVE")
                        .HasColumnType("TEXT");

                    b.Property<string>("PRODUCT_NAME")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PRODUCT_UNID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PSI_TYPE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("REMARK")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("PSI.Core.Entities.PurchaseIngredient", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("ITEM_NAME")
                        .HasColumnType("TEXT");

                    b.Property<double>("ITEM_PERCENT")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PRODUCT_UNID")
                        .HasColumnType("TEXT");

                    b.Property<double>("PURCHASE_WEIGHTNOTE")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PURCHASE_WEIGHTNOTE_UNID")
                        .HasColumnType("TEXT");

                    b.Property<double>("REMAINING_WEIGHT")
                        .HasColumnType("REAL");

                    b.Property<int>("STATUS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PurchaseIngredients");
                });

            modelBuilder.Entity("PSI.Core.Entities.PurchaseWeightNote", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ACTUAL_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<string>("CAR_NO")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CAR_WEIGHT")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("CAR_WEIGHT_TIME")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CONTRACT_UNID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("CUSTOMER_NAME")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CUSTOMER_UNID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DEFECTIVE_REASON")
                        .HasColumnType("TEXT");

                    b.Property<double>("DEFECTIVE_WEIGHT")
                        .HasColumnType("REAL");

                    b.Property<decimal>("DELIVERY_FEE")
                        .HasColumnType("TEXT");

                    b.Property<string>("DOC_NO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EFFECTIVE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("EXCAVATOR_OPERATE_EMPLOYEENO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EXCAVATOR_OPERATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("FAC_NO")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FINALE_DDEFECTIVE_WEIGHT")
                        .HasColumnType("REAL");

                    b.Property<double>("FULL_WEIGHT")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FULL_WEIGHT_TIME")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HAS_TAX")
                        .HasColumnType("INTEGER");

                    b.Property<string>("INPUT_TYPE")
                        .HasColumnType("TEXT");

                    b.Property<int>("NOTE_STATUS")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PAY_TIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("PAY_TYPE")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PRODUCT_ITEM_UNID")
                        .HasColumnType("TEXT");

                    b.Property<string>("REMARK")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SCALE_NO")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("THIRD_WEIGHT_FEE")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TRADE_WEIGHT")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("TRAFIC_UNIT_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UNID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UNIT_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WEIGHT_PRICE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PurchaseWeightNotes");
                });

            modelBuilder.Entity("PSI.Core.Entities.SalesIngredient", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<string>("ITEM_NAME")
                        .HasColumnType("TEXT");

                    b.Property<double>("ITEM_PERCENT")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PRODUCT_UNID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SALES_WEIGHTNOTE_UNID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("SalesIngredients");
                });

            modelBuilder.Entity("PSI.Core.Entities.SalesWeightNote", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CARNO_UNID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CONTRACT_UNID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CUSTOMER_UNID")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DEFECTIVE_WEIGHT")
                        .HasColumnType("TEXT");

                    b.Property<string>("DOC_NO")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EXCAVATOR_OPERATOR_UNID")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("INVOICEPRICE_TAX")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("INVOICE_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<int>("NOTE_STATUS")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PRODUCT_ITEM_UNID")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RECEIVED_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RECEIVED_TIME")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RECEIVED_TYPE")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RECEIVED_UNIT_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<string>("REMARK")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SALES_TIME")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SALES_UNIT_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SALES_WEIGHT")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SCALE_NO")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TAX_RENT")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TRAFIC_FEE")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TRAFIC_FEE_TAX")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TRAFIC_UNIT_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UNID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UPDATE_SALES_TIME")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("SalesWeightNotes");
                });

            modelBuilder.Entity("PSI.Core.Entities.SalesWeightNoteStepData", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<int>("DATA_STEP")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DEFECTIVE_WEIGHT")
                        .HasColumnType("REAL");

                    b.Property<string>("DOC_NO")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DOC_UNID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("INVOICEPRICE_HASTAX")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("INVOICE_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PRODUCT_ITEM_UNID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RECEIVED_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RECEIVED_TIME")
                        .HasColumnType("TEXT");

                    b.Property<int>("RECEIVED_TYPE")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SALES_WEIGHT")
                        .HasColumnType("REAL");

                    b.Property<bool>("TRAFICFEE_HASTAX")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TRAFIC_FEE")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TRAFIC_UNIT_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UNIT_PRICE")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("SalesWeightNotesStepDatas");
                });

            modelBuilder.Entity("PSI.Core.Entities.SeqTypeConfig", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CREATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_TIME")
                        .HasColumnType("TEXT");

                    b.Property<long>("SEQ_NO")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SEQ_TYPE")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPDATE_EMPNO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UPDATE_TIME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("SeqTypeConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
